# Zadanie 1

In [1]:
import numpy.typing as npt
import numpy as np

K = 1000 # liczba epok 
N = 3 # liczba neruonów wejściowych
U = 0.001 # krok treningowym
# omega = np.array([[[0.111,0.222,0.333], 0],[[0.999,0.222,0.888], 1], [[0.555,0.444,0.333], 0], [[0.555,1,0.333], 1]])




In [2]:
from typing import Callable

def liniar_function(scalar: float, input: float = 1.0) -> float:
    return scalar * input

# budowa neuronu

class Neuron:
    def __init__(self, input: np.ndarray[float], weights: np.ndarray[float] = None,  activation_function: Callable = None):
        self.weights = weights
        if self.weights is None:
            self.weights = np.random.rand(N)
        self.inputs = input
        self.activation_function = activation_function
        if self.activation_function is None:
            self.activation_function = liniar_function

    def get_new_input(self, inputs: np.ndarray[float]):
        self.inputs = inputs
        pass


    def calculate_output(self) -> float:
        return self.activation_function(np.dot(self.inputs, self.weights))
        

    def train_neuron(self, desiaier_output: int):
        new_weights = np.arange(N, dtype=float)
        old_output = self.calculate_output()
        for index, w in enumerate(self.weights):
             new_weights[index] = w + U * (desiaier_output - old_output) * self.inputs[index]
        self.weights = new_weights
        pass


In [3]:
neuron = Neuron(input=np.array([0.111,0.222,0.333]))
print(neuron.weights)
print(neuron.inputs)
print(neuron.calculate_output())
neuron.train_neuron(0)
print(neuron.weights)
print(neuron.calculate_output())
neuron.get_new_input(inputs=np.array([0.444,0.222,0.333]))
neuron.train_neuron(0)
print(neuron.inputs)
print(neuron.weights)
print(neuron.calculate_output())
neuron.get_new_input(inputs=np.array([0.111,0.222,0.333]))
print(neuron.calculate_output())


[0.80348093 0.06331209 0.22513809]
[0.111 0.222 0.333]
0.17821265171752915
[0.80346115 0.06327252 0.22507875]
0.17818191110438378
[0.444 0.222 0.333]
[0.80326324 0.06317357 0.22493032]
0.4455752077328088
0.17808854889894143


In [4]:
# class to learn neuron it's weights
class NeuronTrainer:
    def __init__(self, training_inputs: np.ndarray[float], training_outputs: np.ndarray[int], neuron: Neuron = None):
        self.neuron = neuron
        if self.neuron is None:
            self.neuron = Neuron(input = training_inputs[0])
        self.training_inputs = training_inputs,
        self.training_outputs = training_outputs
        if(training_inputs.shape[0] != training_outputs.size):
            raise Exception("Number of traning vectors is not same as desirable outputs")
    
    def train_neruon_with_set(self):
        for traning_index,traning_vector in enumerate(self.training_inputs[0]):
            self.neuron.get_new_input(inputs = traning_vector)
            self.neuron.train_neuron(self.training_outputs[traning_index])
        pass


In [5]:

training = np.array([[0.111, 0.444, 0.999],
                     [0.555, 0.777, 0.999],
                     [0, 0, 0.777],
                     [0.999, 1, 0.122]])

neuronToTrain = Neuron( input = np.array([0.111, 0.444, 0.999]))
print(neuronToTrain.weights)
print(neuronToTrain.inputs)
neuronTrainer = NeuronTrainer(training_inputs = training, training_outputs = np.array([0,0,1,1]), neuron = neuronToTrain )
neuronTrainer.train_neruon_with_set()
print(neuronToTrain.weights)

[0.31977265 0.73341233 0.75152571]
[0.111 0.444 0.999]
[0.31867713 0.73161417 0.74922744]
