# Zadanie 1

In [1]:
import numpy as np

K = 1000 # liczba epok 
N = 5 # liczba neruonów wejściowych
U = 0.1 # krok treningowym




In [2]:
from typing import Callable

def liniar_function(scalar: float, input: float = 1.0) -> float:
    return scalar * input

# budowa neuronu

class Neuron:
    def __init__(self, input: np.ndarray[float] = None, weights: np.ndarray[float] = None,  activation_function: Callable = None):
        self.weights = weights
        if self.weights is None:
            self.weights = np.random.rand(N)
        self.inputs = input
        if self.inputs is None:
            self.inputs = np.random.rand(N)
        self.activation_function = activation_function
        if self.activation_function is None:
            self.activation_function = liniar_function

    def get_new_input(self, inputs: np.ndarray[float]):
        self.inputs = inputs
        pass


    def calculate_output(self) -> float:
        return self.activation_function(np.dot(self.inputs, self.weights))
        
    # def if_training_exceed(self, new_weights: np.ndarray[float]):
    #     for new_w in new_weights:
    #         if new_w < 1 or new_w > -1:
    #             raise Exception("New weight exceed max or min weight value")
    #     pass

    def train_neuron(self, desiaier_output: int):
        new_weights = np.arange(N, dtype=float)
        old_output = self.calculate_output()
        for index, w in enumerate(self.weights):
             new_weights[index] = w + U * (desiaier_output - old_output) * self.inputs[index]
        self.weights = new_weights
        # self.if_training_exceed(new_weights)
        pass


In [3]:
# neurons = Neuron()
# print(neurons.weights)
# print(neurons.inputs)
# print(neurons.calculate_output())
# neurons.train_neuron(0)
# print(neurons.weights)
# print(neurons.calculate_output())
# neurons.get_new_input(inputs = np.random.rand(N))
# neurons.train_neuron(0)
# print(neurons.inputs)
# print(neurons.weights)
# print(neurons.calculate_output())
# neurons.get_new_input(inputs = np.random.rand(N))
# print(neurons.calculate_output())


In [4]:
import random

# Prepare training set
training = np.array([np.random.rand(N) for _ in range(N+2)])

training_outputs = np.array([random.randint(0, 1) for _ in range(N+2)])

smaller_training_outputs = training_outputs[:(N-2)]
smaller_training_set = training[:(N-2)]

equal_training_outputs = training_outputs[:N]
equal_training_set = training[:N]

print(training)
print(training_outputs)

[[0.66439625 0.0857982  0.15106966 0.99606077 0.2579005 ]
 [0.96263339 0.98598734 0.28551143 0.40584611 0.34917426]
 [0.33210573 0.08309996 0.09489606 0.37335958 0.71282335]
 [0.86636575 0.34716994 0.68366159 0.79338479 0.42179703]
 [0.23988198 0.36838828 0.38830914 0.4345658  0.00968345]
 [0.49054145 0.60254652 0.83324181 0.16696891 0.54063175]
 [0.53967897 0.29811076 0.06108676 0.31149877 0.76961738]]
[1 0 1 0 1 0 1]


In [5]:
# class to learn neurons it's weights
class NeuronTrainer:
    def __init__(self, training_inputs: np.ndarray[float], training_outputs: np.ndarray[int], neurons: list[Neuron] = None):
        self.neurons = neurons
        if self.neurons is None:
            self.neurons = [Neuron(input = training_inputs[0])]
        self.training_inputs = training_inputs,
        self.training_outputs = training_outputs
        if(training_inputs.shape[0] != training_outputs.size):
            raise Exception("Number of traning vectors is not same as desirable outputs")

    def train_neurons(self):
        for _ in range(K):
            for neuron in self.neurons:
                self.train_neruon_with_set(neuron)
        pass

    def show_calculate_results(self):
        for training_index, training_input in enumerate(training):
            self.neurons[0].get_new_input(training_input)
            print("result of 1 neuron for traning {} : {}, true class {}".format(training_index, self.neurons[0].calculate_output(), training_outputs[training_index]))
        pass
    

    def show_weights(self):
        for index, neuron in enumerate(self.neurons):
            print("Weights of {} neuron : {}".format(index, neuron.weights))
        pass

    def train_neruon_with_set(self, neuron: Neuron):
        for traning_index,traning_vector in enumerate(self.training_inputs[0]):
            neuron.get_new_input(inputs = traning_vector)
            neuron.train_neuron(self.training_outputs[traning_index])
        pass
    
    def set_other_neurons(self, neurons: list[Neuron]):
        self.neurons = neurons
        pass


In [6]:
# traning with M < N
neurons_to_train_with_smaller_set = [Neuron() for _ in range(N)]  
print("Strating traning with smaller training set")
neuron_trainer_small = NeuronTrainer(training_inputs = smaller_training_set, training_outputs = smaller_training_outputs, neurons = neurons_to_train_with_smaller_set )
print("Starting weights :")
neuron_trainer_small.show_weights()
neuron_trainer_small.train_neurons()
print("Result weights :")
neuron_trainer_small.show_weights()
neuron_trainer_small.show_calculate_results()


Strating traning with smaller training set
Starting weights :
Weights of 0 neuron : [0.91471674 0.26738756 0.67093475 0.51496488 0.62833954]
Weights of 1 neuron : [0.12330715 0.24913362 0.78681771 0.03694352 0.04570919]
Weights of 2 neuron : [0.07859884 0.14450006 0.07192034 0.69822704 0.75285871]
Weights of 3 neuron : [0.30325429 0.43385165 0.84578937 0.53225635 0.30866787]
Weights of 4 neuron : [0.4767591  0.97178992 0.19111935 0.06137412 0.95241037]
Result weights :
Weights of 0 neuron : [ 0.17224509 -0.92353712  0.43605748  0.6330276   1.04067194]
Weights of 1 neuron : [-0.10454934 -0.78386901  0.68703041  0.76492507  1.05085268]
Weights of 2 neuron : [-0.23621526 -0.52842429 -0.03620862  0.92967872  1.09240539]
Weights of 3 neuron : [-0.24317822 -0.68118858  0.66681409  0.84864921  1.06230846]
Weights of 4 neuron : [-0.14166713 -0.59115663 -0.05495665  0.8765159   1.08600976]
result of 1 neuron for traning 0 : 1.0000000000000677, true class 1
result of 1 neuron for traning 1 : 1.5

In [7]:
# traning with M == N
neurons_to_train_with_equal_set = [Neuron() for _ in range(N)]  
print("Strating traning with equal training set")
neuron_trainer_equal = NeuronTrainer(training_inputs = equal_training_set, training_outputs = equal_training_outputs, neurons = neurons_to_train_with_equal_set )
print("Starting weights :")
neuron_trainer_equal.show_weights()
neuron_trainer_equal.train_neurons()
print("Result weights :")
neuron_trainer_equal.show_weights()
neuron_trainer_equal.show_calculate_results()

Strating traning with equal training set
Starting weights :
Weights of 0 neuron : [0.1025951  0.16997609 0.91925595 0.48433482 0.19460663]
Weights of 1 neuron : [0.36264729 0.61916183 0.21114394 0.01764543 0.34994773]
Weights of 2 neuron : [0.08262052 0.99141109 0.01299759 0.91304433 0.68819035]
Weights of 3 neuron : [0.81751081 0.12656456 0.83312391 0.26191387 0.84140717]
Weights of 4 neuron : [0.20933899 0.01332017 0.87458573 0.53994333 0.06004788]
Result weights :
Weights of 0 neuron : [-3.88591658  2.2080165  -0.70494785  3.15163444  1.39284621]
Weights of 1 neuron : [-3.88500458  2.20740717 -0.70486702  3.15111597  1.3926208 ]
Weights of 2 neuron : [-3.89154723  2.21177847 -0.70544701  3.15483547  1.39423785]
Weights of 3 neuron : [-3.8817433   2.20522824 -0.7045779   3.14926194  1.39181476]
Weights of 4 neuron : [-3.88469581  2.20720088 -0.70483963  3.15094043  1.39254449]
result of 1 neuron for traning 0 : 0.9995943739689463, true class 1
result of 1 neuron for traning 1 : 0.000

In [8]:
# traning with M > N
neurons_to_train_with_bigger_set = [Neuron() for _ in range(N)]  
print("Strating traning with bigger training set")
neuron_trainer_bigger = NeuronTrainer(training_inputs = training, training_outputs = training_outputs, neurons = neurons_to_train_with_bigger_set )
print("Starting weights :")
neuron_trainer_bigger.show_weights()
neuron_trainer_bigger.train_neurons()
print("Result weights :")
neuron_trainer_bigger.show_weights()
neuron_trainer_bigger.show_calculate_results()

Strating traning with bigger training set
Starting weights :
Weights of 0 neuron : [0.62439602 0.17724165 0.66494679 0.61729654 0.17130688]
Weights of 1 neuron : [0.22663849 0.57404901 0.97481504 0.02773133 0.85537348]
Weights of 2 neuron : [0.39307689 0.38951633 0.17413568 0.06031125 0.23548074]
Weights of 3 neuron : [0.2697606  0.3564954  0.04210324 0.91433673 0.09118951]
Weights of 4 neuron : [0.41487483 0.53624086 0.4962842  0.22743453 0.4181273 ]
Result weights :
Weights of 0 neuron : [-3.78059978  2.18462192 -0.97091391  3.11239367  1.66222308]
Weights of 1 neuron : [-3.78272529  2.1860741  -0.97123925  3.11368706  1.66267633]
Weights of 2 neuron : [-3.78118819  2.18502393 -0.97100398  3.11275172  1.66234856]
Weights of 3 neuron : [-3.78437843  2.18720355 -0.97149229  3.11469301  1.66302885]
Weights of 4 neuron : [-3.78210233  2.18564849 -0.9711439   3.11330799  1.66254349]
result of 1 neuron for traning 0 : 1.057766086866461, true class 1
result of 1 neuron for traning 1 : 0.081